### ISSUE TITLE
Why not alpine?

### ISSUE THREAD

**Issue by fodma1** [amancevice/docker-pandas#2]
I was looking for an alpine image containing pandas. Your repo is the first google hit, but then I saw that it's debian based. What was the reason to ditch alpine? Could you please update the project description?

Thank you

**Comment by amancevice** [comment]
This is apparently a hot issue today. See comments on https://github.com/amancevice/pandas/commit/b282fd413ca9cbe0a5134776d2853e25c6ee0cde

I suppose the answer is to create an alpine image in addition to the Debian ones.

**Comment by amancevice** [comment]
I am building these images. It takes some time, but they should be available later today.

**Comment by amancevice** [comment]
Okay, these images are available using the `-alpine` suffix. Check the README for usage.
