### ISSUE TITLE
multiarm issue

### ISSUE THREAD

**Issue by clementnuss** [amancevice/docker-pandas#28]
hi,

I've just tried running `amancevice/pandas:slim` (it resolved to `sha256:4d8685ae3ca4b2fb39548a79db0c7c1871540f6343c4c251b10edc16d84dd686`) on an amd64 machine, but I get an `exec /bin/sh: exec format error`, and [on dockerhub](https://hub.docker.com/layers/amancevice/pandas/slim/images/sha256-4d8685ae3ca4b2fb39548a79db0c7c1871540f6343c4c251b10edc16d84dd686?context=explore) it seems it actually is an `arm64` image. 

can you have a look ?

**Comment by amancevice** [comment]
Just pushed some changes. Can you confirm it's resolved for you?

**Comment by clementnuss** [comment]
yep, perfect! thanks a lot :)
