### ISSUE TITLE
0.15.1

### ISSUE THREAD

**Issue by myoung34** [amancevice/docker-pandas#3]
For reasons outside my control, we require 0.15.1
Instead of forking yours, would you be willing to build and push a 0.15 (including alpine) container so your docker stats can get some love from our CI server?

**Comment by amancevice** [comment]
Sure, I am pushing builds for `0.15.1` on `debian:stretch` and `alpine:3.6` as I type.

I had some trouble getting `debian:slim` builds to work and I'm disinclined to troubleshoot unless you'd really like to use the slim tags.

**Comment by myoung34** [comment]
nah, stretch would be perfect!

**Comment by amancevice** [comment]
done!
